name: Add Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the environment to add'
        required: true
      reviewers:
        description: 'Comma-separated list of GitHub usernames for required reviewers'
        required: true

jobs:
  add_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        id: setup
        run: |
          echo "## Setting up environment variables"
          environment_name="${{ github.event.inputs.environment_name }}"
          reviewers="${{ github.event.inputs.reviewers }}"
          echo "ENVIRONMENT_NAME=$environment_name" >> $GITHUB_ENV
          echo "REVIEWERS=$reviewers" >> $GITHUB_ENV

      - name: Add environment with reviewers
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ENVIRONMENT_NAME: ${{ env.ENVIRONMENT_NAME }}
          REVIEWERS: ${{ env.REVIEWERS }}
        run: |
          # Convert the comma-separated reviewers into JSON array format
          reviewers_array=$(echo $REVIEWERS | jq -R 'split(",")')

          # Add environment
          curl -X PUT -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/environments/$ENVIRONMENT_NAME \
            -d "{}"

          # Set deployment protection rules with required reviewers
          curl -X PUT -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/environments/$ENVIRONMENT_NAME/deployment_protection_rules \
            -d "{\"required_reviewers\": $reviewers_array}"
