name: Add Environment Variables

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name (e.g., owner/repo)'
        required: true
      env_vars:
        description: 'JSON object containing environment variables (e.g., {"VAR1":"value1","VAR2":"value2"})'
        required: true
        default: '{"VAR1":"default_value1","VAR2":"default_value2"}'

jobs:
  add-env-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set environment variables
        id: set-env
        run: |
          echo "${{ github.event.inputs.env_vars }}" > env_vars.json
          jq -c 'to_entries | .[] | { name: .key, value: .value }' env_vars.json > processed_vars.json
          
          # Loop through each environment variable and set it in the repository
          while IFS= read -r line; do
            var_name=$(echo "$line" | jq -r '.name')
            var_value=$(echo "$line" | jq -r '.value')
            echo "Setting variable $var_name in repository ${{ github.event.inputs.repo_name }}"
            curl -X PUT \
              -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"name\":\"$var_name\",\"value\":\"$var_value\"}" \
              "https://api.github.com/repos/${{ github.event.inputs.repo_name }}/actions/secrets/$var_name"
          done < <(jq -c '.[]' processed_vars.json)
